PREFIX edintinm: <https://edint.github.io/edint-ontologia-inmuebles/ontology/inmobiliaria#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX catastro: <https://edint.github.io/edint-ontologia-catastro/ontology/catastro#>

# CQ07: How is the location of a property specified?
# SPANISH: ¿Cómo se especifica la ubicación de un inmueble?

SELECT ?listing ?listingId ?cadastralEntity ?hasGeometry ?wktCoordinate ?address
WHERE {
  ?listing a edintinm:RealEstateListing ;
           dcterms:identifier ?listingId ;
           edintinm:refersToCadastralEntity ?cadastralEntity .
  
  OPTIONAL {
    ?cadastralEntity geo:hasGeometry ?hasGeometry .
    
    OPTIONAL {
      ?hasGeometry geo:asWKT ?wktCoordinate .
    }
  }
  
  OPTIONAL {
    ?cadastralEntity catastro:hasAddress ?address .
  }
}

ORDER BY ?listingId
